apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-frontend
  namespace: video-processor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: video-frontend
  template:
    metadata:
      labels:
        app: video-frontend
    spec:
      containers:
      - name: frontend
        image: video-frontend:latest
        imagePullPolicy: Never  # For local images
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
