apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-worker
  namespace: video-processor
spec:
  replicas: 2
  selector:
    matchLabels:
      app: video-worker
  template:
    metadata:
      labels:
        app: video-worker
    spec:
      containers:
      - name: worker
        image: video-worker:latest
        imagePullPolicy: Never  # For local images
        env:
        - name: API_URL
          value: "http://api-service:8080"
        volumeMounts:
        - name: storage
          mountPath: /storage
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "1000m"  # FFmpeg can be CPU intensive
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: video-storage-pvc
