apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-worker
  namespace: video-processor
spec:
  replicas: 2
  selector:
    matchLabels:
      app: video-worker
  template:
    metadata:
      labels:
        app: video-worker
    spec:
      containers:
      - name: worker
        image: ffmpeg-worker:latest
        imagePullPolicy: Never  # Use local image only
        env:
        - name: API_URL
          value: "http://api-service:8080"
        volumeMounts:
        - name: video-storage
          mountPath: /storage
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      volumes:
      - name: video-storage
        persistentVolumeClaim:
          claimName: video-storage-pvc 
