apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: video-processor
spec:
  selector:
    app: video-api
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: video-processor
spec:
  selector:
    app: video-frontend
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer
