apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: video-processor
  labels:
    app: video-processing-system
    component: api
spec:
  selector:
    app: video-api
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
  sessionAffinity: None

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: video-processor
  labels:
    app: video-processing-system
    component: frontend
spec:
  selector:
    app: video-frontend
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  type: LoadBalancer
  sessionAffinity: None
